version: "3.8"
services:
  web:
    build: Website
    image: zornco-site
    expose:
      - "5000"
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: zornco-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - web
